apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stunner-application
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
  project: default
  sources:
    - chart: stunner-gateway-operator
      repoURL: https://l7mp.io/stunner
      targetRevision: 1.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: stunner-system