apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password-connect.svc.cluster.local:8080
      vaults:
        kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-connect-token
            key: token
            namespace: external-secrets