apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-login
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli:8087/object/item/{{ .remoteRef.key }}"
      headers:
        Content-Type: application/json
      result:
        jsonPath: "$.data.login.{{ .remoteRef.property }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1passwordconnect.svc.cluster.local:8080
      vaults:
        kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: 1passwordconnect
            key: token
            namespace: external-secrets