apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
# spec:
#   provider:
#     onepassword:
#       connectHost: http://onepassword-connect.1passwordconnect.svc.cluster.local:8080
#       vaults:
#         kubernetes: 1
#       auth:
#         secretRef:
#           connectTokenSecretRef:
#             name: 1passwordconnect
#             key: token
#             namespace: external-secrets

spec:
  provider:
    onepasswordSDK:
      vault: kubernetes
      auth:
        serviceAccountSecretRef:
          name: 1passwordconnect
          key: token
          namespace: external-secrets