apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    name: "jellyfin"
    port: 8096
    targetPort: 8096
  type: ClusterIP