apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-application
  namespace: argocd
spec:
  project: default
  sources:
    - chart: prometheus-node-exporter
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 4.45.2
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true