apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
  hostnames:
    - "plex2.batlab.io"
  rules:
    - backendRefs:
        - name: plex-application-plex-media-server
          port: 32400