apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: batlab-certificate
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: batlab-certificate
    creationPolicy: Owner
    template:
      data:
        batlab-io.pem: "{{ .certificate | toString }}"
        batlab-io.key: "{{ .privatekey | toString }}"
  data:
    - secretKey: certificate
      remoteRef:
        key: batlab-wildcard-cert
        property: certificate
    - secretKey: privatekey
      remoteRef:
        key: batlab-wildcard-cert
        property: privatekey
