apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-appset
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/mpearlst/kubernetes-configs.git
        revision: HEAD
        directories:
          - path: funland/*/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mpearlst/kubernetes-configs.git
        path: '{{.path.path}}'
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{index .path.segments 1}}'
      ignoreDifferences:
        - group: postgresql.cnpg.io
          kind: Cluster
          jqPathExpressions:
            - .spec.affinity
            - .spec.backup.target
            - .spec.bootstrap.initdb.encoding
            - .spec.bootstrap.initdb.localeCType
            - .spec.bootstrap.initdb.localeCollate
            - .spec.enablePDB
            - .spec.enableSuperuserAccess
            - .spec.failoverDelay
            - .spec.imageName
            - .spec.logLevel
            - .spec.maxSyncReplicas
            - .spec.minSyncReplicas
            - .spec.monitoring
            - .spec.postgresql
            - .spec.primaryUpdateMethod
            - .spec.primaryUpdateStrategy
            - .spec.resources
            - .spec.smartShutdownTimeout
            - .spec.startDelay
            - .spec.stopDelay
            - .spec.switchoverDelay
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true