apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-application
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.4.4
    helm:
      valuesObject:
        persistence:
          type: pvc
          enabled: true
          storageClassName: longhorn
        deploymentStrategy:
          type: Recreate
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true