apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
  hostnames:
    - "grafana.batlab.io"
  rules:
    - backendRefs:
        - name: grafana-application
          port: 80