apiVersion: v1
kind: Service
metadata:
  name: adguard-home-setup
spec:
  selector:
    app: adguard
  ports:
  - name: adguard-setup
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: adguard
spec:
  loadBalancerIP: 192.168.10.35
  selector:
    app: adguard
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns
  type: LoadBalancer