---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocis-secret
  namespace: owncloud
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: ocis-secret
    creationPolicy: Owner
    template:
      data:
        idm_admin_password: "{{ .idm_admin_password | toString }}"
  data:
    - secretKey: idm_admin_password
      remoteRef:
        key: ocis
        property: idm_admin_password
