apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: senk0-pkcs12-secret
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 7b301901-3512-4f3f-ad2c-d534e3acc7dc
        property: password