# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: batlab-pkcs12-secret
#   labels:
#     external-secrets.io/type: webhook
# spec:
#   refreshInterval: "5m"
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: bitwarden-login
#   target:
#     creationPolicy: Owner
#   data:
#     - secretKey: password
#       sourceRef:
#         storeRef:
#           name: bitwarden-login
#           kind: ClusterSecretStore  # or SecretStore
#       remoteRef:
#         key: f1ffd739-0962-4348-93d1-3b70866b9570
#         property: password
# ---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: batlab-pkcs12-secret
  namespace: certificate
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: pkcs12-secret
      remoteRef:
        key: cloudflare
        property: batlab-pkcs12-secret
