# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: batlab
# spec:
#   secretName: batlab
#   keystores:
#     pkcs12:
#       create: true
#       passwordSecretRef:
#         name: batlab-pkcs12-secret
#         key: password
#   issuerRef:
#     name: letsencrypt-dns
#     kind: ClusterIssuer
#   commonName: '*.batlab.io'
#   dnsNames:
#   - '*.batlab.io'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: batlab
spec:
  secretName: batlab
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: cloudflare
        key: pkcs12-secret
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: '*.batlab.io'
  dnsNames:
  - '*.batlab.io'