apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: batlab
spec:
  secretName: batlab
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: '*.batlab.io'
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
  - '*.batlab.io'
  - 'batlab.io'
  keystores:
    pkcs12:
      create: true
      profile: Modern2023
      passwordSecretRef:
        name: pkcs12-password
        key: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pkcs12-password
  namespace: certificate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: pkcs12-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: batlab-pkcs12-password
        property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: batlab-wildcard-cert
  namespace: certificate
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: batlab
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: batlab-wildcard-cert
          property: certificate
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: batlab-wildcard-cert
          property: privatekey
    - match:
        secretKey: keystore.p12
        remoteRef:
          remoteKey: batlab-wildcard-cert
          property: keystore-p12