apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: senk0
spec:
  secretName: senk0
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: senk0-pkcs12-secret
        key: password
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: '*.senk0.com'
  dnsNames:
  - '*.senk0.com'