apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nextcloud-pdb
  namespace: nextcloud
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nextcloud-notify-push-pdb
  namespace: nextcloud
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud-notify-push
