---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-application
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.13.0
    helm:
      valuesObject:
        args:
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
          - --kubelet-use-node-status-port
          - --metric-resolution=15s
        metrics:
          enabled: true
        serviceMonitor:
          enabled: false
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true