---
kind: Namespace
apiVersion: v1
metadata:
  name: postgres
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: cluster01
  namespace: postgres
spec:
  teamId: acid
  volume:
    size: 5Gi
    storageClass: longhorn
  numberOfInstances: 2
  preparedDatabases:
    authentik:
      defaultUsers: true
      extensions: {}
      schemas:
        # still uses public schema...
        # https://github.com/goauthentik/authentik/issues/9212
        public:
          defaultRoles: false
          defaultUsers: false
    synapse:
      defaultUsers: true
      extensions: {}
      schemas:
        # still uses public schema...
        # https://github.com/zoriya/Kyoo/issues/536
        public:
          defaultRoles: false
          defaultUsers: false
    vikunja:
      defaultUsers: true
      extensions: {}
      schemas:
        # still uses public schema...
        # https://community.vikunja.io/t/postgres-database-has-error-pq-relation-tasks-does-not-exist/1333
        public:
          defaultRoles: false
          defaultUsers: false
  postgresql:
    version: "16"
    parameters:
      password_encryption: scram-sha-256
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster01.authentik.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik-owner-user.cluster01.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres.cluster01.authentik.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres.cluster01.authentik.owner
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster01.synapse.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: synapse-owner-user.cluster01.credentials.postgresql.acid.zalan.do
  # template:
  #   data:
  #     _metadata_origin: "push"
  #     test123: "{{ .username | toString }}"
  #     username: "{{ .username | toString }}"
  #     password: "{{ .password | toString }}"
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres.cluster01.synapse.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres.cluster01.synapse.owner
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster01.vikunja.owner
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: vikunja-owner-user.cluster01.credentials.postgresql.acid.zalan.do
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres.cluster01.vikunja.owner
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres.cluster01.vikunja.owner
          property: password