apiVersion: v1
kind: Service
metadata:
  name: privatebin-service
  namespace: privatebin
spec:
  selector:
    app: privatebin
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP