apiVersion: v1
kind: Namespace
metadata:
  name: synapse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: synapse
  labels:
    app: synapse
spec:
  selector:
    matchLabels:
      app: synapse
  replicas: 1
  template:
    metadata:
      labels:
        app: synapse
    spec:
      initContainers:
      - name: synapse-generate
        image: ghcr.io/element-hq/synapse:latest
        env:
          - name: SYNAPSE_SERVER_NAME
            value: "matrix.batlab.io"
          - name: SYNAPSE_REPORT_STATS
            value: "no"
          - name: SYNAPSE_PUBLIC_BASEURL  # Add this line
            value: "https://matrix.batlab.io"
        args: ["generate"]
        volumeMounts:
        - mountPath: /data
          name: synapse-data
      containers:
      - name: synapse
        image: matrixdotorg/synapse:latest
        env:
          - name: "TZ"
            value: "America/New_York"
          - name: SYNAPSE_DB_USER
            valueFrom:
              secretKeyRef:
                name: synapse-db-secret
                key: synapse-db-user
          - name: SYNAPSE_DB_PASS
            valueFrom:
              secretKeyRef:
                name: synapse-db-secret
                key: synapse-db-pass
        ports:
        - containerPort: 8008
        volumeMounts:
        - mountPath: /data
          name: synapse-data
        resources:
          limits:
            cpu: 250m
            memory: 768Mi
            ephemeral-storage: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
            ephemeral-storage: 16Mi
      volumes:
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: synapse-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeMode: Filesystem