apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-db-secret
  namespace: synapse
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: synapse-db-user
      remoteRef:
        key: postgres.cluster01.synapse.owner
        property: username
    - secretKey: synapse-db-pass
      remoteRef:
        key: postgres.cluster01.synapse.owner
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-registration-secret
  namespace: synapse
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: synapse-registration-secret
      remoteRef:
        key: synapse-registration-secret
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-macaroon-secret
  namespace: synapse
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: synapse-macaroon-secret
      remoteRef:
        key: synapse-macaroon-secret
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: batlab-wildcard-cert
  namespace: synapse
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: batlab-wildcard-cert
        property: certificate
    - secretKey: tls.key
      remoteRef:
        key: batlab-wildcard-cert
        property: privatekey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-config
  namespace: synapse
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        homeserver.yaml: |-
          server_name: "matrix.batlab.io"
          pid_file: /data/homeserver.pid
          listeners:
            - port: 8008
              tls: false
              type: http
              x_forwarded: true
              resources:
                - names: [client]
                  compress: false
            - port: 8448
              tls: true
              type: http
              x_forwarded: true
              resources:
                - names: [federation]
                  compress: false
          tls_certificate_path: /tls/tls.crt
          tls_private_key_path: /tls/tls.key
          database:
            name: psycopg2
            args:
              database: synapse
              host: cluster01.postgres
              user: {{ .synapse_db_user | toString }}
              password: {{ .synapse_db_pass | toString }}
              port: 5432
              cp_min: 5
              cp_max: 10
          enable_registration: true
          enable_registration_without_verification: true

          log_config: "/data/batlab.io.log.config"
          media_store_path: /data/media_store
          registration_shared_secret: "X:SARxitOh96wR.y-lJSj9genR=UB6QT4Kdk8:C2mhg^pa*d#&"
          report_stats: false
          macaroon_secret_key: "9OLPo6z=;JrWS9aSr.ph;Ibd3HNhY;bxMmGev1JO~5xs6;o;GQ"
          form_secret: "gZzt2P@x6G9MzxBQwL;dzVz-5qDIh-Ipj,z;WW~Ts49T&2sWj8"
          signing_key_path: "/data/batlab.io.signing.key"
          trusted_key_servers:
            - server_name: "matrix.org"
  data:
    - secretKey: synapse_db_pass
      remoteRef:
        key: postgres.cluster01.synapse.owner
        property: password
    - secretKey: synapse_db_user
      remoteRef:
        key: postgres.cluster01.synapse.owner
        property: username
        