apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: matrix
  namespace: synapse
spec:
  parentRefs:
    - name: external
      namespace: gateway
      sectionName: https
  hostnames:
    - "matrix.batlab.io"
  rules:
    - backendRefs:
        - name: synapse
          port: 8008