apiVersion: v1
kind: Service
metadata:
  name: synapse
  namespace: synapse
spec:
  selector:
    app: synapse
  ports:
  - protocol: TCP
    port: 8008
    targetPort: 8008
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-federation
  namespace: synapse
spec:
  selector:
    app: synapse
  ports:
  - protocol: TCP
    port: 8448
    targetPort: 8448
  type: LoadBalancer