apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-db-secret
  namespace: synapse
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: synapse-db-user
      remoteRef:
        key: postgres.cluster01.synapse.owner
        property: username
    - secretKey: synapse-db-pass
      remoteRef:
        key: postgres.cluster01.synapse.owner
        property: password