apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: matrix-client
  namespace: synapse
spec:
  parentRefs:
    - name: external
      namespace: gateway
      sectionName: https
  hostnames:
    - "matrix.batlab.io"
  rules:
    - backendRefs:
        - name: synapse
          port: 8008
---
# HTTPRoute for batlab.io to serve .well-known delegation
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: matrix-wellknown
  namespace: synapse
spec:
  parentRefs:
    - name: external
      namespace: gateway
      sectionName: https
  hostnames:
    - "batlab.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/matrix
      backendRefs:
        - name: synapse
          port: 8008