apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-secrets
  namespace: pocket-id
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: pocket-id-secrets
    creationPolicy: Owner
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: pocket-id-secrets
        property: encryption_key
