apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
  hostnames:
    - "prometheus.batlab.io"
  rules:
    - backendRefs:
        - name: prometheus-application
          port: 80