apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-application
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
  project: default
  sources:
    - chart: netbird
      repoURL: https://netbirdio.github.io/helms
      targetRevision: "v0.1.11"
      helm:
        values: |
          management:
            persistentVolume:
              storageClass: longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: netbird