apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-config
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: recyclarr.yml
      remoteRef:
        key: recyclarr
        property: recyclarr_yml
