apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        secrets.yml: |-
          radarr_url: http://radarr.media.svc.cluster.local:7878
          radarr_apikey: {{ .radarr_api_key | toString }}
          sonarr_url: http://sonarr.media.svc.cluster.local:8989
          sonarr_apikey: {{ .sonarr_api_key | toString }}
  data:
    - secretKey: radarr_api_key
      remoteRef:
        key: radarr
        property: api_key
    - secretKey: sonarr_api_key
      remoteRef:
        key: sonarr
        property: api_key
