---
kind: Namespace
apiVersion: v1
metadata:
  name: immich
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.11.13"
    path: /mnt/tank/immich
  mountOptions:
    - nfsvers=4.2
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-library-nfs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        DB_URL: "postgresql://{{ .immich_db_user }}:{{ .immich_db_password }}@immich-dbc-rw.postgres:5432/immich"
        DB_HOSTNAME: "immich-dbc-rw.postgres"
        DB_PORT: "5432"
        DB_USERNAME: "{{ .immich_db_user | toString }}"
        DB_PASSWORD: "{{ .immich_db_password | toString }}"
        DB_DATABASE_NAME: "immich"
        IMMICH_AUTH_OIDC_CLIENT_ID: "{{ .oidc_client_id | toString }}"
        IMMICH_AUTH_OIDC_CLIENT_SECRET: "{{ .oidc_client_secret | toString }}"
  data:
    - secretKey: immich_db_user
      remoteRef:
        key: immich-db-credentials
        property: username
    - secretKey: immich_db_password
      remoteRef:
        key: immich-db-credentials
        property: password
    - secretKey: oidc_client_id
      remoteRef:
        key: immich-authentik-oidc
        property: client_id
    - secretKey: oidc_client_secret
      remoteRef:
        key: immich-authentik-oidc
        property: client_secret
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-application
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: immich
    repoURL: ghcr.io/immich-app/immich-charts
    targetRevision: 0.10.1
    helm:
      valuesObject:
        env:
          DB_VECTOR_EXTENSION: "vchord"
          OAUTH_ENABLED: "true"
          OAUTH_ISSUER_URL: "https://auth.batlab.io/application/o/immich/"
          OAUTH_SCOPE: "openid email profile"
          OAUTH_BUTTON_TEXT: "Login with Authentik"
          OAUTH_AUTO_LAUNCH: "false"
        controllers:
          main:
            containers:
              main:
                image:
                  tag: v2.1.0
                env:
                  - name: OAUTH_CLIENT_ID
                    valueFrom:
                      secretKeyRef:
                        name: immich-secret
                        key: IMMICH_AUTH_OIDC_CLIENT_ID
                  - name: OAUTH_CLIENT_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: immich-secret
                        key: IMMICH_AUTH_OIDC_CLIENT_SECRET
                envFrom:
                  - secretRef:
                      name: immich-secret
        server:
          enabled: true
          ingress:
            enabled: false
        immich:
          persistence:
            library:
              existingClaim: immich-library
        valkey:
          enabled: true
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
