---
kind: Namespace
apiVersion: v1
metadata:
  name: immich
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.11.13"
    path: /mnt/tank/immich
  mountOptions:
    - nfsvers=4.2
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-library-nfs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        DB_URL: "postgresql://{{ .immich_db_user }}:{{ .immich_db_password }}@immich-dbc-rw.postgres:5432/immich"
        DB_HOSTNAME: "immich-dbc-rw.postgres"
        DB_PORT: "5432"
        DB_USERNAME: "{{ .immich_db_user | toString }}"
        DB_PASSWORD: "{{ .immich_db_password | toString }}"
        DB_DATABASE_NAME: "immich"
  data:
    - secretKey: immich_db_user
      remoteRef:
        key: immich-db-credentials
        property: username
    - secretKey: immich_db_password
      remoteRef:
        key: immich-db-credentials
        property: password
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-application
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: immich
    repoURL: ghcr.io/immich-app/immich-charts
    targetRevision: 0.10.1
    helm:
      valuesObject:
        image:
          tag: v1.128.0
        env:
          DB_HOSTNAME:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_HOSTNAME
          DB_PORT:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_PORT
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_USERNAME
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_PASSWORD
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_DATABASE_NAME
          DB_VECTOR_EXTENSION: "vchord"
        immich:
          persistence:
            library:
              existingClaim: immich-library
        valkey:
          enabled: true
        server:
          ingress:
            enabled: false
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
