apiVersion: v1
kind: Namespace
metadata:
  name: excalidraw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: excalidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
        - name: excalidraw-container
          image: excalidraw/excalidraw:latest # Using the official image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-service
  namespace: excalidraw
spec:
  selector:
    app: excalidraw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: excalidraw-httproute
  namespace: excalidraw
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
  hostnames:
    - "excalidraw.batlab.io"
  rules:
    - backendRefs:
        - name: excalidraw-service
          port: 80