apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-application
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  project: default
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.26.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true