---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-config
  namespace: ntfy
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        server.yml: |-
          base-url: 'https://ntfy.batlab.io'
          upstream-base-url: "https://ntfy.sh"
          behind-proxy: true
          cache-file: "/var/cache/ntfy/cache.db"
          auth-file: '/var/lib/ntfy/auth/user.db'
          auth-default-access: 'deny-all'
          enable-signup: false
          #web-push-public-key: BF730NmK8COJ-0lDL_E576A-_kB2y0Us78rby_oBhYUKOg2wBCTZ0kvZfdibxWmKvLzjiaHucAAeMCrP_Ie0BR8
          #web-push-private-key: {{ .ntfy_web_push_private_key | toString }}
          #web-push-file: /var/cache/ntfy/webpush.db # or similar
          #web-push-email-address: ntfy@batlab.io
  data:
    - secretKey: ntfy_web_push_private_key
      remoteRef:
        key: ntfy
        property: web_push_private_key
    