apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-dbc
  namespace: postgres
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  monitoring:
    enablePodMonitor: true
  storage:
    size: 10Gi
    storageClass: longhorn-single
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
        - "REVOKE ALL ON SCHEMA public FROM PUBLIC;"
        - "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC;"
        - "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC;"
        - "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM PUBLIC;"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-db-credentials
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: immich-dbc-app
  template:
    data:
      _metadata_origin: "push"
      username: "{{ .username | toString }}"
      password: "{{ .password | toString }}"
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: immich-db-credentials
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: immich-db-credentials
          property: password
