apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: synapse-dbc
  namespace: postgres
spec:
  instances: 3
  storage:
    size: 5Gi
    storageClass: longhorn-single
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: synapse
      owner: synapse
      postInitSQL:
        - "REVOKE ALL ON SCHEMA public FROM PUBLIC;"
        - "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC;"
        - "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC;"
        - "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM PUBLIC;"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: synapse-db-credentials
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRefs:
    - name: 1password
      kind: ClusterSecretStore
  selector:
    secret:
      name: synapse-dbc-app
  template:
    data:
      _metadata_origin: "push"
      username: "{{ .username | toString }}"
      password: "{{ .password | toString }}"
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: synapse-db-credentials
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: synapse-db-credentials
          property: password
