apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-ntfy-bridge-config
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        config.yaml: |-
          http:
            addr: ":8000"
          ntfy:
            baseurl: http://ntfy.ntfy.svc.cluster.local
            auth:
              token: {{ .ntfy_token | toString }}
            notification:
              topic: alerts
              priority: |
                status == "firing" ? "high" : "default"
              tags:
                - tag: rotating_light
                  condition: status == "firing"
                - tag: white_check_mark
                  condition: status == "resolved"
              templates:
                title: |
                  {{ "{{" }} if eq .Status "resolved" {{ "}}" }}Resolved: {{ "{{" }} end {{ "}}" }}{{ "{{" }} index .Annotations "summary" {{ "}}" }}
                description: |
                  {{ "{{" }} index .Annotations "description" {{ "}}" }}
                headers:
                  X-Click: |
                    {{ "{{" }} .GeneratorURL {{ "}}" }}
  data:
    - secretKey: ntfy_token
      remoteRef:
        key: alertmanager-ntfy-bridge
        property: ntfy_token
