apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng-application
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
  project: default
  sources:
    - chart: searxng
      repoURL: https://charts.searxng.org
      targetRevision: 1.0.1
      helm:
        values: |
          env:
            BASE_URL: "https://searxng.batlab.io"
          redis:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: searxng