apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-configsecrets
  namespace: vikunja
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: jwtsecret
      remoteRef:
        key: vikunja
        property: jwtsecret
    - secretKey: postgrespassword
      remoteRef:
        key: vikunja-db-credentials
        property: password
    - secretKey: postgresuser
      remoteRef:
        key: vikunja-db-credentials
        property: username
