apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-sso
  namespace: vikunja
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        config.yaml: |-
          auth:
            openid:
              enabled: true
              redirecturl: https://vikunja.batlab.io/auth/openid/
              providers:
                - name: authentik
                  authurl: https://auth.batlab.io/application/o/vikunja/
                  logouturl: https://auth.batlab.io/application/o/vikunja/end-session/
                  clientid: "{{ .client_id | toString }}"
                  clientsecret: "{{ .client_secret | toString }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: vikunja-sso
        property: vikunja_client_id
    - secretKey: client_secret
      remoteRef:
        key: vikunja-sso
        property: vikunja_client_secret
