apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-operator-secret
  namespace: cloudflare
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-operator-api-token-secret
      remoteRef:
        key: cloudflare-operator
        property: password
    - secretKey: cloudflare-operator-tunnel-name-secret
      remoteRef:
        key: cloudflare-operator
        property: tunnelName
    - secretKey: cloudflare-operator-account-id-secret
      remoteRef:
        key: cloudflare-operator
        property: accountId
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-operator-application
  namespace: argocd
spec:
  destination:
    namespace: cloudflare
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cloudflare-tunnel-ingress-controller
    repoURL: https://helm.strrl.dev
    targetRevision: 0.0.18
    helm:
      valuesObject:
        cloudflare:
          secretRef:
            name: cloudflare-operator-secret
            accountIDKey: cloudflare-operator-account-id-secret
            tunnelNameKey: cloudflare-operator-tunnel-name-secret
            apiTokenKey: cloudflare-operator-api-token-secret
            #accountId: ""
            #tunnelName: ""
            #apiToken: ""
        cloudflared:
          image:
            tag: 2025.10.0
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true