apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-application
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: cnpg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: "0.23.2"
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg