apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-application
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: "0.23.2"
      # helm:
      # valuesObject:
      #   crds:
      #     enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true