apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-application
  namespace: argocd
spec:
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: postgres-operator
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    targetRevision: 1.14.0
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true