apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-configuration
configuration:
  aws_or_gcp:
    aws_region: us-west-1
    kube_iam_role: postgres-pod-role
    wal_s3_bucket: your-backup-path

  s3_endpoint:
    valueFrom:
      secretKeyRef:
        name: postgres-backup
        key: s3_endpoint
  s3_access_key_id:
      valueFrom:
      secretKeyRef:
        name: postgres-backup
        key: s3_access_key_id
  s3_secret_access_key:
      valueFrom:
      secretKeyRef:
        name: postgres-backup
        key: s3_secret_access_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backup
  namespace: postgres
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: postgres-backup
    creationPolicy: Owner
  data:
    - secretKey: s3_endpoint
      remoteRef:
        key: postgres-backup
        property: s3_endpoint
    - secretKey: s3_access_key_id
      remoteRef:
        key: postgres-backup
        property: s3_access_key_id
    - secretKey: s3_secret_access_key
      remoteRef:
        key: postgres-backup
        property: s3_secret_access_key